// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VerstaOrders;

#nullable disable

namespace VerstaOrders.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VerstaOrders.Model.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressReceiver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressSender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ProductWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("TownReceiver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TownSender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("a582d854-2216-42b7-95b9-c9b2c2d7d669"),
                            AddressReceiver = "Невский пр., д. 25",
                            AddressSender = "ул. Тверская, д. 10",
                            OrderNumber = "ORD-0520260001",
                            PickupDate = new DateTime(2026, 5, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            ProductWeight = 15.5,
                            TownReceiver = "Санкт-Петербург",
                            TownSender = "Москва"
                        },
                        new
                        {
                            OrderId = new Guid("5c5759c6-4b4e-4150-bbe0-912c1c8f8c34"),
                            AddressReceiver = "пр. Ленина, 100",
                            AddressSender = "ул. Баумана, 5",
                            OrderNumber = "ORD-0520260002",
                            PickupDate = new DateTime(2026, 5, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            ProductWeight = 8.1999999999999993,
                            TownReceiver = "Екатеринбург",
                            TownSender = "Казань"
                        },
                        new
                        {
                            OrderId = new Guid("9288547b-e8f0-4d05-add5-5f29a4a3f94b"),
                            AddressReceiver = "Океанский пр., 7",
                            AddressSender = "Красный пр., 12",
                            OrderNumber = "ORD-0520260003",
                            PickupDate = new DateTime(2026, 5, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            ProductWeight = 42.0,
                            TownReceiver = "Владивосток",
                            TownSender = "Новосибирск"
                        });
                });

            modelBuilder.Entity("VerstaOrders.Model.OrderDateSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrentValue"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrderDateSequences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentValue = 3,
                            Month = 5,
                            Year = 2026
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
